---

# Cleaning server of existing database and installation

- name: Check if pre-existing MySQL service exists
  stat: path=/etc/init.d/mysqld
  register: service_status

- name: Stop any pre-existing MySQL service
  service: name=mysqld state=stopped
  when: service_status.stat.exists
  register: service_stopped

- name: Remove any pre-existing mysql install
  yum:
    name: mysql*
    autoremove: no
    state: absent

- name: Remove any pre-existing mariadb install
  yum:
    name: mariadb*
    autoremove: no
    state: absent

- name: Remove any pre-existing data
  file:
    path: /var/lib/mysql
    state: absent

- name: Remove pre-existing .my.cnf
  file:
    path: /root/.my.cnf
    state: absent


# Installing database

- name: install mysql repo
  yum:
    name: https://dev.mysql.com/get/mysql80-community-release-el7-2.noarch.rpm
   
- name: disable mysql current repos
  command: /usr/bin/yum-config-manager --disable mysql8*-community && /usr/bin/yum-config-manager --disable mysql5*-community  
  
- name: enable repo for desired mysql version
  command: /usr/bin/yum-config-manager --enable mysql{{MySQL_version}}-community
  
- name: install mysql server
  yum:
    name: ['mysql-community-server']
    state: latest  
  
- name: remove any pre-existing content in /var/lib/mysql
  file:
    path: /var/lib/mysql
    state: absent

- name: Initialize 5.6 or older
  command: mysql_install_db --user=mysql
  when: (MySQL_version == "56") or (MySQL_version == "55")

- name: native password mysql 8.0
  lineinfile:
    path: /etc/my.cnf
    line: default-authentication-plugin=mysql_native_password
    state: present
  when: (MySQL_version == "80")

- name: Initialize 5.7 and newer
  command: mysqld --initialize-insecure --user=mysql
  when: (MySQL_version == "57") or (MySQL_version == "80")

- name: start and enable mysql
  service:
    name: mysqld
    state: started
    enabled: yes

# updating root password

- name: add root pw 5.6 or older
  command: mysqladmin -u root --skip-password password ("{{ mysql_root_password }}")
  when: (MySQL_version == "56") or (MySQL_version == "55")


- name: add root pw 5.7 and newer
  command: mysql -u root --skip-password --execute "ALTER USER 'root'@'localhost' IDENTIFIED BY ("{{ mysql_root_password }}");"
  when: (MySQL_version == "57") or (MySQL_version == "80")

- name: Add password.my.cnf
  include: password.my.cnf.yml
#  when: mysql_local_my_cnf.stat.exists == False


- name: Restart MySQL
  service:
    name: mysqld
    state: restarted

- name: Disallow remote root MySQL logins, remove anonymous users and drop test databases
  command: >
    mysql -e '
    DELETE FROM mysql.user WHERE User="root" AND Host NOT IN ("localhost", "127.0.0.1", "::1");
    DELETE FROM mysql.user WHERE User="";
    DROP DATABASE IF EXISTS test;
    DELETE FROM mysql.db WHERE DB="test" OR DB="test\\_%";
    FLUSH PRIVILEGES;
    '
  when: (MySQL_version == "56") or (MySQL_version == "55")



