---

- name: create my.cnf
  file:
    path: ~/.my.cnf
    state: touch

- name: add lines
  blockinfile:
    path: ~/.my.cnf
    block: |
      [client]
      user=root
      password={{ mysql_root_password }}
