---

- name: install MySQL-python
  yum:
    name: MySQL-python
    state: latest

- name: Copy .sql file to host
  copy:
    src: employees_nokeys.sql.gz 
    dest: /tmp

- name: Import databases
  mysql_db:
    state: import
    name: employees
    target: /tmp/employees_nokeys.sql.gz

