---

- name: install MySQL-python
  yum:
    name: MySQL-python
    state: latest


- name: Import databases
  mysql_db:
    state: import
    name: employees
    target: complete_db_from_55.sql.gz


