---

- name: install MySQL-python
  yum:
    name: MySQL-python
    state: latest

- name: Copy .sql file to host
  copy:
    src: complete_db_from_55.sql.gz
    dest: /tmp

- name: Import databases
  mysql_db:
    state: import
    name: employees
    target: /tmp/complete_db_from_55.sql.gz


